# This file was generated by GoReleaser. DO NOT EDIT.
cask "live-pr" do
  version "0.10.0"

  on_macos do
    on_arm do
      sha256 "91119999aea1133c5a5f20f7b4d594bedc634a0de7d18ad1c9f9abf06c8e0b08"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dce583c24103fc6498adf70dfc62f903f3cfef514168cc6e6da13cc39ec34073"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5f45d5c080539ba2d216f908c8ce52d44330fdeb05bd4f79b0761a7363dc2069"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c83a3d7c1648b3821e345a916499856df2d80417b4bedd6b447bda6689579b47"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "live-pr"
  desc "Live PR review TUI with a decision timeline for humans and agents"
  homepage "https://github.com/shonenm/live-pr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "live-pr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/live-pr"]
    end
  end

  # No zap stanza required
end
