# This file was generated by GoReleaser. DO NOT EDIT.
cask "live-pr" do
  version "0.10.4"

  on_macos do
    on_arm do
      sha256 "d2fce8d47343287be2dfe9f8077621ee941349bd89a8b5c8943b97c458afe94b"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e5db3bb4158cb5761be6e7f2c0970cb458e9357da62e9adb31df4ba5d2e6853d"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "84e7e8ab66a8d128b57a27318c1d65496017015de0f3c996c4a5d22b2cf2105a"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "929555bb8a40fabfe146d8ce03c69a6b6cf0c470fa9adce1a42ceb38bb98e72a"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "live-pr"
  desc "Live PR review TUI with a decision timeline for humans and agents"
  homepage "https://github.com/shonenm/live-pr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "live-pr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/live-pr"]
    end
  end

  # No zap stanza required
end
