# This file was generated by GoReleaser. DO NOT EDIT.
cask "live-pr" do
  version "0.9.8"

  on_macos do
    on_arm do
      sha256 "de775fa2ac560706b8c31dea9bf073c36bfa12beecff948b8a6a1a5425716704"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "38128918a54b7cae82360d625467a7a954f2079b1932122fc16e84989bdc6f06"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bd54045d8d78af61d8e9f67ee7af7f117865fd1cf6175ef7f1fc549cc951a62a"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "114c975d1fdeeeb9e32b3027fd3b7b0e4ca7e5ea61d128b72ba4c7bf969c71f3"
      url "https://github.com/shonenm/live-pr/releases/download/v#{version}/live-pr_#{version}_Linux_amd64.tar.gz"
    end
  end

  name "live-pr"
  desc "Live PR review TUI with a decision timeline for humans and agents"
  homepage "https://github.com/shonenm/live-pr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "live-pr"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/live-pr"]
    end
  end

  # No zap stanza required
end
